CREATE TABLE markets (
    market_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_name TEXT,
    market_is_active BOOLEAN,
    market_account TEXT,
    market_bids_account TEXT,
    market_asks_account TEXT,
    market_url TEXT,
    market_base_deposit NUMERIC,
    market_quote_deposit NUMERIC,
    market_taker_fees NUMERIC,
    market_maker_fees NUMERIC,
    market_base_lot_size NUMERIC,
    market_quote_lot_size NUMERIC,
    market_start_slot BIGINT,
    market_end_slot BIGINT DEFAULT NULL,
    market_create_signature TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    ended_at TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name TEXT,
    asset_slug TEXT,
    asset_description TEXT,
    asset_mint_account TEXT,
    asset_decimals NUMERIC,
    asset_account TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE instruments (
    instrument_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_name TEXT,
    base_asset_id BIGINT REFERENCES assets (asset_id),
    base_name TEXT,
    quote_asset_id BIGINT REFERENCES assets (asset_id),
    quote_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_account TEXT,
    order_account_num BIGINT,
    instrument_id BIGINT REFERENCES instruments (instrument_id),
    market_id BIGINT REFERENCES markets (market_id),
    order_side INT, -- fix enum, bid, ask
    order_owner_account TEXT, -- fix could be account
    order_base_size NUMERIC,
    order_quote_size NUMERIC,
    order_price NUMERIC,
    order_slot BIGINT,
    order_blocktime BIGINT,
    order_state INT, -- fix enum, partially filled, filled, cancelled, failed
    order_signature TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE order_books (
    order_book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_book_blocktime BIGINT,
    order_book_slot BIGINT,
    order_book_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_signature TEXT,
    event_type BIGINT,
    event_originator TEXT, -- like is this twapmarket or obmarket
    event_signer TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE trades (
    trade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders (order_id),
    trade_base_size NUMERIC,
    trade_quote_size NUMERIC,
    trade_price NUMERIC,
    trade_taker_account TEXT, -- make account?
    trade_maker_account TEXT,
    trade_fee NUMERIC,
    trade_blocktime BIGINT,
    trade_slot BIGINT,
    trade_signature TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_public_key TEXT,
    account_details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);