CREATE TABLE markets (
    market_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_name TEXT,
    market_account TEXT,
    market_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name TEXT,
    asset_description TEXT,
    account TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE instruments (
    instrument_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_name TEXT,
    base_asset_id BIGINT REFERENCES assets (asset_id),
    base_name TEXT,
    quote_asset_id BIGINT REFERENCES assets (asset_id),
    quote_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_account TEXT,
    order_account_num BIGINT,
    instrument_id BIGINT REFERENCES instruments (instrument_id),
    market_id BIGINT REFERENCES markets (market_id),
    order_side INT, -- fix enum
    order_maker TEXT, -- fix could be account
    order_taker TEXT, -- fix could be account
    order_base_size NUMERIC,
    order_quote_size NUMERIC,
    order_price NUMERIC,
    order_slot BIGINT,
    order_blocktime BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE order_books (
    order_book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_book_blocktime BIGINT,
    order_book_slot BIGINT,
    order_book_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_signature TEXT,
    event_type BIGINT,
    event_originator TEXT, -- like is this twapmarket or obmarket
    -- TODO: should this have the signer so we can join on accounts?
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE trades (
    trade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders (order_id),
    trade_base_size NUMERIC,
    trade_quote_size NUMERIC,
    trade_taker TEXT, -- make account?
    trade_maker TEXT,
    trade_fee NUMERIC,
    trade_blocktime BIGINT,
    trade_slot BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_public_key TEXT,
    account_details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);